EMAIL_SENDER = "Nigerian Voice Bank<noreply@nigerianvoicebank.com>"
RECENT_VOICE_CLIPS_DISPLAY_LIMIT = 5
TOP_VOICE_CLIPS_DISPLAY_LIMIT = 5
EVENTS_DISPLAY_LIMIT = 2
WELCOME_MSG_SUBJECT = "Your Nigerian Voice Bank Account"
MUSICBOX_ALBUMS_PAGINATE_BY = 20
VOICECLIP_LIST_PAGINATE_BY = 10
